# Generated by Django 5.2.3 on 2025-06-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="название товара"),
                ),
                ("price", models.PositiveIntegerField(verbose_name="цена")),
                (
                    "price_discount",
                    models.PositiveIntegerField(verbose_name="цена со скидкой"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=10, verbose_name="рейтинг"
                    ),
                ),
                (
                    "feedbacks",
                    models.PositiveIntegerField(verbose_name="количество отзывов"),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
